inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 1.9
  Include:
    - "**/*.cap"
    - "Gemfile"
    - "Rakefile"
    - "appsignal.gemspec"
  Exclude:
    - "tmp/**/*"
    - "gemfiles/vendor/**/*"
    - "vendor/**/*"
    - "benchmark.rake"
  DisplayCopNames: true
  UseCache: true
  CacheRootDirectory: ./tmp

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/IndentArray:
  EnforcedStyle: consistent

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodMissing:
  Exclude:
    - "lib/appsignal/extension.rb"
    - "lib/appsignal/transaction.rb"

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/FileName:
  Exclude:
    - "ext/Rakefile"

Metrics/BlockLength:
  Exclude:
    - "Rakefile"

# Metrics/LineLength:
#   Max: 80
