inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 1.9
  Include:
    - "Gemfile"
    - "**/*.cap"
  Exclude:
    - "tmp/**/*"
    - "gemfiles/vendor/**/*"
    - "vendor/**/*"
  DisplayCopNames: true
  UseCache: true
  CacheRootDirectory: ./tmp

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/IndentArray:
  EnforcedStyle: consistent

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodMissing:
  Exclude:
    - "lib/appsignal/extension.rb"
    - "lib/appsignal/transaction.rb"

# Metrics/LineLength:
#   Max: 80
