default: &defaults
  push_api_key: "abc"
  name: "TestApp"

production:
  <<: *defaults
  active: true

development:
  <<: *defaults
  active: true

test:
  <<: *defaults
  endpoint: "http://localhost:3000"
  debug: true
  active: true

old_config:
  api_key: "def"
  active: true
  ignore_exceptions:
    - StandardError

old_config_mixed_with_new_config:
  push_api_key: "ghi"
  api_key: "def"
  active: true
  ignore_errors:
    - NoMethodError
  ignore_exceptions:
    - StandardError
