name: Ruby

on:
  push:
    branches:
      - master
      - develop
  pull_request: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        ruby:
        - "1.9.3"
        - "2.6.4"
        gem:
        - "no_dependencies"
        - "sinatra"
