name: Ruby

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macOS-10.14
          # - windows-2016
        ruby:
          - "2.3.x"
          - "2.4.x"
          - "2.5.x"
          - "2.6.x"
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }} test suite
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: "Install bundle"
      run: |
        gem update --no-document --system
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: "Install extension"
      run: bundle exec rake extension:install
    - name: "RSpec"
      run: bundle exec rake test
